[[packages]]
repository = "https://github.com/mystenlabs/sui"
paths = [
    "crates/sui-framework/packages/deepbook",
    "crates/sui-framework/packages/move-stdlib",
    "crates/sui-framework/packages/sui-framework",
    "crates/sui-framework/packages/sui-system",
]

[[packages]]
repository = "https://github.com/sea-protocol/seaprotocol"
paths = [
    "src",
]
